name: Deployment .NET Core 7.0

on:
  push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: dotNet Build Restore
        run: dotnet build
      # プログラム実行
      - name: dotNet Run
        run: dotnet run --project ./csharp/HatopopoNote/HatopopoNote/
