name: Deployment .NET Core 7.0

on:
  push:
   branches: [ main ]

jobs:
  build-csharp:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore ./csharp/HatopopoNote/HatopopoNote/
      - name: Build
        run: dotnet build --no-restore ./csharp/HatopopoNote/HatopopoNote/
      - name: Test
        run: dotnet test --no-build --verbosity normal ./csharp/HatopopoNote/HatopopoNote/
      # プログラム実行
      - name: Run
        run: dotnet run --project ./csharp/HatopopoNote/HatopopoNote/
  deployment:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name:
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
  
