name: Deployment .NET Core 7.0

on:
  push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore --project ./csharp/HatopopoNote/HatopopoNote/
      - name: Build
        run: dotnet build --no-restore --project ./csharp/HatopopoNote/HatopopoNote/
      - name: Test
        run: dotnet build --no-build --verbosity normal --project ./csharp/HatopopoNote/HatopopoNote/
      # プログラム実行
      - name: Run
        run: dotnet run --project ./csharp/HatopopoNote/HatopopoNote/
